parameters:
  rm_service_connection: ''
  base_name: ''
  model_name: ''
  model_metadata_artifact: 'model-metadata'
  AKS_CLUSTER: ''

jobs:
  - job: DeployProdJob
    steps:
      - task: AzureCLI@1
        displayName: 'Install the CLI'
        inputs:
          azureSubscription: ${{ parameters.rm_service_connection }}
          scriptLocation: inlineScript
          inlineScript: 'az extension add -n azure-cli-ml'

      - download: current
        displayName: Download artifact model metadata
        artifact: ${{ parameters.model_metadata_artifact }}

      - task: AzureCLI@1
        displayName: 'Deploy the model to AKS'
        inputs:
          azureSubscription: ${{ parameters.rm_service_connection }}
          scriptLocation: inlineScript
          inlineScript: 'az ml model deploy -n ${{ parameters.model_name }}-service-aks --ct ${{ parameters.AKS_CLUSTER }} -f $(Pipeline.Workspace)/model-metadata/model.json --ic  $(Build.SourcesDirectory)/code/score/inferenceConfig.yml --dc  $(Build.SourcesDirectory)/code/score/deploymentConfig.yml --overwrite --workspace-name ${{ parameters.base_name }}-aml-ws --resource-group ${{ parameters.base_name }}-aml-rg'