parameters:
  rm_service_connection: ''
  workspace: ''
  resource_group: ''
  model_name: ''
  aml_compute_cluster: ''
  dataset_name: ''
  run_metadata_artifact: 'run-metadata'

jobs:
  - job: TrainJob
    displayName: Training in Azure ML Compute
    steps:
      - task: AzureCLI@1
        displayName: 'Install the CLI'
        inputs:
          azureSubscription: ${{ parameters.rm_service_connection }}
          scriptLocation: inlineScript
          inlineScript: 'az extension add -n azure-cli-ml'

      - task: AzureCLI@1
        displayName: 'Run training'
        inputs:
          azureSubscription: ${{ parameters.rm_service_connection }}
          scriptLocation: inlineScript
          inlineScript: 'az ml run submit-script --workspace-name ${{ parameters.workspace }} --resource-group ${{ parameters.resource_group }} -e ${{ parameters.model_name }}-experiment -d code/train/train_conda_env.yml --ct ${{ parameters.aml_compute_cluster }} --source-directory code/train -t run.json train_model.py --MODEL_NAME ${{ parameters.model_name }} --DATASET_NAME ${{ parameters.dataset_name }}'

      - publish: $(System.DefaultWorkingDirectory)/run.json
        displayName: Publish run metadata artifact
        artifact: ${{ parameters.run_metadata_artifact }}