trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: templates/common/Variables.yml

stages:

  - stage: Training
    displayName: Train the model
    jobs:
      - template: templates/ci/Train.yml
        parameters:
          rm_service_connection: '${{ variables.RM_SERVICE_CONNECTION }}'
          workspace: '${{ variables.WORKSPACE }}'
          resource_group: '${{ variables.RESOURCE_GROUP }}'
          model_name: '${{ variables.MODEL_NAME }}'
          aml_compute_cluster: '${{ variables.AML_COMPUTE_CLUSTER }}'
          dataset_name: '${{ variables.DATASET_NAME }}'

  - stage: RegisterModel
    displayName: Register the model
    jobs:
      # Perform an empty deploy job for approval (This is the way in Azure Devops)
      - deployment: Approval
        displayName: Approval for model registration
        environment: 'Test'

      - template: templates/cd/Register.yml
        parameters:
          rm_service_connection: '${{ variables.RM_SERVICE_CONNECTION }}'
          workspace: '${{ variables.WORKSPACE }}'
          resource_group: '${{ variables.RESOURCE_GROUP }}'
          model_name: '${{ variables.MODEL_NAME }}'

  - stage: DeployToTest
    displayName: Deploy model to Test (Azure Container Instance)
    jobs:
      - template: templates/cd/DeployToTest.yml
        parameters:
          rm_service_connection: '${{ variables.RM_SERVICE_CONNECTION }}'
          workspace: '${{ variables.WORKSPACE }}'
          resource_group: '${{ variables.RESOURCE_GROUP }}'
          model_name: '${{ variables.MODEL_NAME }}'

  - stage: DeployToProd
    displayName: Deploy to Prod with approval
    jobs:
      # Perform an empty deploy job for approval (This is the way in Azure Devops)
      - deployment: Approval
        displayName: Approval for rolling out to production
        environment: 'Prod'

      - template: templates/cd/DeployToProd.yml
        parameters:
          rm_service_connection: '${{ variables.RM_SERVICE_CONNECTION }}'
          workspace: '${{ variables.WORKSPACE }}'
          resource_group: '${{ variables.RESOURCE_GROUP }}'
          model_name: '${{ variables.MODEL_NAME }}'
          aks_cluster: '${{ variables.AKS_CLUSTER }}'
