trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: mlops-aml-vg

steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: '$(RM_SERVICE_CONNECTION)'
    action: 'DeleteRG'
    resourceGroupName: '$(BASE_NAME)-aml-rg'
    location: $(LOCATION)
  displayName: 'Tear down the environment (delete the resource group will all resources in it)'