trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: mlops-aml-vg

stages:
  - stage: CreateEnvironment
    displayName: "Create the Environment"
    jobs:
      - job: CreateEnvironmentJob
        steps:
          - task: AzureResourceGroupDeployment@2
            displayName: 'Deploy MLOps resources to Azure'
            inputs:
              azureSubscription: '$(RM_SERVICE_CONNECTION)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: '$(BASE_NAME)-aml-rg'
              location: $(LOCATION)
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/mlops_pipelines/arm-templates/EnvCreateARMTemplete.json'
              overrideParameters: '-baseName $(BASE_NAME) -location $(LOCATION)'
              deploymentMode: 'Incremental'

  - stage: ProvisionCompute
    displayName: "Create Azure ML compute & AKS clusters"
    jobs:
      # Provision Azure ML compute cluster
      - template: templates/common/ProvisionAMLComputeCluster.yml
        parameters:
          rm_service_connection: '$(RM_SERVICE_CONNECTION)'
          base_name: '$(BASE_NAME)'
          train_cluster_sku: '$(TRAIN_CLUSTER_SKU)'
          train_cluster: '$(TRAIN_CLUSTER)'

      # Provision AKS cluster
      - template: templates/common/ProvisionAKSCluster.yml
        parameters:
          rm_service_connection: '$(RM_SERVICE_CONNECTION)'
          base_name: '$(BASE_NAME)'
          aks_scoring_cluster: '$(AKS_SCORING_CLUSTER)'
