trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: templates/common/Variables.yml

stages:
  - stage: CreateEnvironment
    displayName: "Create the Environment"
    jobs:
      - job: CreateEnvironmentJob
        steps:
          - task: AzureResourceGroupDeployment@2
            displayName: 'Deploy MLOps resources to Azure'
            inputs:
              azureSubscription: '${{ variables.RM_SERVICE_CONNECTION }}'
              action: 'Create Or Update Resource Group'
              resourceGroupName: '${{ variables.BASE_NAME }}-aml-rg'
              location: ${{ variables.LOCATION }}
              templateLocation: 'Linked artifact'
              csmFile: '$(Build.SourcesDirectory)/mlops_pipelines/arm-templates/EnvCreateARMTemplete.json'
              overrideParameters: '-baseName ${{ variables.BASE_NAME }} -location ${{ variables.LOCATION }}'
              deploymentMode: 'Incremental'

  - stage: ProvisionCompute
    displayName: "Create Azure ML compute & AKS clusters"
    jobs:
      # Provision Azure ML compute cluster
      - template: templates/setup/ProvisionAMLComputeCluster.yml
        parameters:
          rm_service_connection: '${{ variables.RM_SERVICE_CONNECTION }}'
          base_name: '${{ variables.BASE_NAME }}'
          AML_COMPUTE_SKU: '${{ variables.AML_COMPUTE_SKU }}'
          AML_COMPUTE_CLUSTER: '${{ variables.AML_COMPUTE_CLUSTER }}'

      # Provision AKS cluster
      - template: templates/setup/ProvisionAKSCluster.yml
        parameters:
          rm_service_connection: '${{ variables.RM_SERVICE_CONNECTION }}'
          base_name: '${{ variables.BASE_NAME }}'
          AKS_CLUSTER: '${{ variables.AKS_CLUSTER }}'